<option value="blank">Select one</option>
<option value="varchar">Varchar</option>
<option value="text">Text</option>
<option value="mediumText">Medium text</option>
<option value="longText">Long text</option>
<option value="boolean">Boolean</option>
<option value="integer">Integer</option>
<option value="decimal">Decimal</option>
<option value="double">Double</option>
<option value="float">Float</option>
<option value="tinyInteger">Tiny Integer</option>
<option value="enum">Enum</option>